version: "3.3"

services:
  db:
    image: postgres:15
    container_name: to_do_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - to_do_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to_do_web
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"

volumes:
  to_do_db:
    driver: local
